# Generated by Django 6.0.7 on 2026-07-27 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0003_alter_mailbox_daily_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailbox",
            name="daily_limit",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.CreateModel(
            name="SendVerdict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "response",
                    models.CharField(
                        choices=[
                            ("deferred", "Deferred (4xx)"),
                            ("quota_exceeded", "Daily quota exceeded"),
                            ("blocked", "Blocked for reputation"),
                            ("refused", "Refused (5xx)"),
                            ("auth_failed", "Authentication failed"),
                            ("transport", "Transport failure (no SMTP response)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("smtp_code", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("detail", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mailbox",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verdicts",
                        to="emails.mailbox",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["mailbox", "created_at"],
                        name="emails_send_mailbox_9ec659_idx",
                    )
                ],
            },
        ),
    ]
