# Generated by Django 6.0.7 on 2026-08-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0004_alter_mailbox_daily_limit_sendverdict"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailbox",
            name="unsub_scan_uid",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mailbox",
            name="unsub_scan_uidvalidity",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
