# Generated by Django 6.0.6 on 2026-08-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_mailbox_unsub_scan_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='next_send_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
