# Generated by Django 6.0.7 on 2026-08-13 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0006_mailbox_next_send_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted by the receiver"),
                            ("deferred", "Deferred (4xx)"),
                            ("rejected", "Rejected (5xx)"),
                            ("bounced", "Bounced (non-delivery report)"),
                            ("error", "No answer from the receiver"),
                        ],
                        max_length=10,
                    ),
                ),
                ("response", models.CharField(blank=True, default="", max_length=20)),
                ("smtp_code", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "enhanced_status",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("detail", models.CharField(blank=True, default="", max_length=255)),
                ("queue_id", models.CharField(blank=True, default="", max_length=128)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FolderCoverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folder", models.CharField(max_length=255)),
                ("uidvalidity", models.PositiveBigIntegerField(default=0)),
                ("last_uid", models.PositiveBigIntegerField(default=0)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Folder coverage",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "Received"), ("out", "Sent")], max_length=3
                    ),
                ),
                ("message_id", models.CharField(max_length=998)),
                (
                    "from_address",
                    models.CharField(blank=True, default="", max_length=320),
                ),
                (
                    "to_address",
                    models.CharField(blank=True, default="", max_length=320),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=998)),
                (
                    "in_reply_to",
                    models.CharField(blank=True, default="", max_length=998),
                ),
                ("references_ids", models.JSONField(blank=True, default=list)),
                ("raw", models.BinaryField(blank=True, null=True)),
                ("body_text", models.TextField(blank=True, default="")),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("folder", models.CharField(blank=True, default="", max_length=255)),
                ("uid", models.PositiveBigIntegerField(blank=True, null=True)),
                ("uidvalidity", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("human_reply", "Human reply"),
                            ("bounce", "Non-delivery report"),
                            ("auto_reply", "Automatic reply"),
                            ("opt_out", "Opt-out"),
                            ("unrelated", "Unrelated"),
                            ("outbound", "Sent by us"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("classified_at", models.DateTimeField(blank=True, null=True)),
                ("classifier_version", models.PositiveSmallIntegerField(default=0)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name="sendverdict",
            name="emails_send_mailbox_9ec659_idx",
        ),
        migrations.RemoveField(
            model_name="mailbox",
            name="unsub_scan_uid",
        ),
        migrations.RemoveField(
            model_name="mailbox",
            name="unsub_scan_uidvalidity",
        ),
        migrations.AddField(
            model_name="foldercoverage",
            name="mailbox",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coverage",
                to="emails.mailbox",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="mailbox",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="emails.mailbox",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deliveryevent",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_events",
                to="emails.message",
            ),
        ),
        migrations.AddField(
            model_name="deliveryevent",
            name="reported_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="emails.message",
            ),
        ),
        migrations.AddField(
            model_name="thread",
            name="mailbox",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threads",
                to="emails.mailbox",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="thread",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="emails.thread",
            ),
        ),
        migrations.RemoveField(
            model_name="sendverdict",
            name="mailbox",
        ),
        migrations.AddConstraint(
            model_name="foldercoverage",
            constraint=models.UniqueConstraint(
                fields=("mailbox", "folder"), name="uniq_mailbox_folder"
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryevent",
            index=models.Index(
                fields=["message", "occurred_at"], name="emails_deli_message_903736_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["classifier_version", "classified_at"],
                name="emails_mess_classif_a1d42c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["processed_at"], name="emails_mess_process_eea432_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["thread", "sent_at"], name="emails_mess_thread__465db0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["mailbox", "direction", "sent_at"],
                name="emails_mess_mailbox_6f3889_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                fields=("mailbox", "message_id"), name="uniq_mailbox_message_id"
            ),
        ),
        migrations.DeleteModel(
            name="SendVerdict",
        ),
    ]
