# Generated by Django 6.0.7 on 2026-08-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_pivot_external_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="external_id",
            field=models.CharField(
                help_text="Message identity, used for dedup (per deal): the RFC-5322 Message-ID of the email. (Legacy pre-pivot rows hold the retired channel's message URN.)",
                max_length=300,
                verbose_name="External message id",
            ),
        ),
    ]
