# Generated by Django 6.0.7 on 2026-08-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_alter_chatmessage_external_id"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="chatmessage",
            name="uniq_deal_external_id",
        ),
        migrations.DeleteModel(
            name="ChatMessage",
        ),
    ]
