# Generated by Django 6.0.3 on 2026-06-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_repoint_campaign_fk_to_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='api_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_info',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
