# Generated by Django 6.0.6 on 2026-06-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0012_lead_api_email_lead_contact_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="state",
            field=models.CharField(
                choices=[
                    ("Qualified", "Qualified"),
                    ("Ready to Email", "Ready To Email"),
                    ("Emailed", "Emailed"),
                    ("Ready to Connect", "Ready To Connect"),
                    ("Pending", "Pending"),
                    ("Connected", "Connected"),
                    ("Completed", "Completed"),
                    ("Failed", "Failed"),
                ],
                default="Qualified",
                max_length=20,
            ),
        ),
    ]
