# Generated by Django 6.0.6 on 2026-07-15 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_campaign_country_code_discoveryquery'),
        ('crm', '0014_pivot_lead_reshape'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='discovered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.discoveryquery'),
        ),
    ]
