# Generated by Django 6.0.6 on 2026-07-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0015_lead_discovered_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="state",
            field=models.CharField(
                choices=[
                    ("Qualified", "Qualified"),
                    ("Ready to Find Email", "Ready To Find Email"),
                    ("Finding Email", "Finding Email"),
                    ("Ready to Email", "Ready To Email"),
                    ("Emailed", "Emailed"),
                    ("No Email (BetterContact)", "No Email Bettercontact"),
                    ("Completed", "Completed"),
                    ("Failed", "Failed"),
                ],
                default="Qualified",
                max_length=32,
            ),
        ),
    ]
