# Generated by Django 6.0.7 on 2026-07-29 11:12

import django.db.models.deletion
from django.db import migrations, models


def drop_stale_provenance(apps, schema_editor):
    """Clear ``discovered_by`` before it is re-pointed at ``QueryNode``.

    The column holds ``DiscoveryQuery`` ids, and that table is being dropped with the
    rest of the clause lattice — so every value in it is about to dangle. Provenance is
    the only thing lost: ``discovered_by`` is never read by qualify, promote or enrich (a
    lead advances on its own P over the global pool), so nulling it costs the walk
    nothing and the leads themselves are untouched.
    """
    apps.get_model("crm", "Lead").objects.update(discovered_by=None)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_keyword_querynode_remove_clause_uniq_clause_and_more"),
        ("crm", "0017_migrate_no_email_failures"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="source_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(drop_stale_provenance, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="lead",
            name="discovered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="core.querynode",
            ),
        ),
    ]
