# Generated by Django 6.0.7 on 2026-08-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0018_lead_source_fields_alter_lead_discovered_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="state",
            field=models.CharField(
                choices=[
                    ("Qualified", "Qualified"),
                    ("Ready to Find Email", "Ready To Find Email"),
                    ("Finding Email", "Finding Email"),
                    ("Ready to Email", "Ready To Email"),
                    ("Emailed", "Emailed"),
                    ("No Email (BetterContact)", "No Email Bettercontact"),
                    ("Unsubscribed", "Unsubscribed"),
                    ("Completed", "Completed"),
                    ("Failed", "Failed"),
                ],
                default="Qualified",
                max_length=32,
            ),
        ),
    ]
