# Generated by Django 6.0.6 on 2026-08-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_delete_task_drop_action_fraction'),
        ('crm', '0019_alter_deal_state'),
        ('emails', '0006_mailbox_next_send_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='next_follow_up_at',
        ),
        migrations.AddField(
            model_name='deal',
            name='lookup_attempt',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deal',
            name='lookup_request_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='deal',
            name='not_before',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='email_message_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=300),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['state', 'not_before'], name='deal_state_not_before_idx'),
        ),
    ]
