# Generated by Django 6.0.7 on 2026-08-13 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0020_deal_not_before_and_lookup_handle"),
        ("emails", "0007_deliveryevent_foldercoverage_message_thread_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deal",
            name="email_message_id",
        ),
        migrations.AddField(
            model_name="deal",
            name="thread",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deals",
                to="emails.thread",
            ),
        ),
    ]
