# Generated by Django 6.0.6 on 2026-06-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_engine_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="finder_api_key",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
