# Generated by Django 6.0.6 on 2026-07-07 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pivot_email_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='campaign_objective',
            new_name='campaign_target',
        ),
    ]
