# Generated by Django 6.0.6 on 2026-07-15 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_campaign_objective_campaign_campaign_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.CreateModel(
            name='DiscoveryQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.JSONField(default=dict)),
                ('params_hash', models.CharField(max_length=64)),
                ('offset', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fetched', 'Fetched'), ('retired', 'Retired')], default='pending', max_length=10)),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_queries', to='core.campaign')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.discoveryquery')),
            ],
            options={
                'verbose_name': 'Discovery Query',
                'verbose_name_plural': 'Discovery Queries',
                'indexes': [models.Index(fields=['campaign', 'status'], name='discovery_camp_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'params_hash', 'offset'), name='uniq_discovery_node')],
            },
        ),
    ]
