# Generated by Django 6.0.6 on 2026-07-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_clause_is_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='discovery_minted_at_qualified',
            field=models.IntegerField(default=0),
        ),
    ]
