# Generated by Django 6.0.7 on 2026-07-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_collapse_prescreen_empties"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="anchor_embeddings",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="anchor_profiles",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
