# Generated by Django 6.0.7 on 2026-07-29 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_campaign_anchor_embeddings_campaign_anchor_profiles"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("lead_job_title", "lead_job_title"),
                            ("lead_seniority", "lead_seniority"),
                            ("lead_location", "lead_location"),
                        ],
                        max_length=32,
                    ),
                ),
                ("token", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="QueryNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_key", models.CharField(max_length=64)),
                ("next_offset", models.IntegerField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("frontier", "frontier"),
                            ("fired", "fired"),
                            ("drained", "drained"),
                            ("dead", "dead"),
                        ],
                        default="frontier",
                        max_length=16,
                    ),
                ),
                ("leads_found", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Query Node",
                "verbose_name_plural": "Query Nodes",
            },
        ),
        migrations.RemoveConstraint(
            model_name="clause",
            name="uniq_clause",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="clauses",
        ),
        migrations.RemoveField(
            model_name="emptyclauseset",
            name="clauses",
        ),
        migrations.RemoveIndex(
            model_name="discoveryquery",
            name="discovery_camp_exhausted_idx",
        ),
        migrations.RemoveConstraint(
            model_name="discoveryquery",
            name="uniq_discovery_node",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="discovery_minted_at_qualified",
        ),
        migrations.AddField(
            model_name="campaign",
            name="headcount_max",
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name="campaign",
            name="headcount_min",
            field=models.IntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name="keyword",
            constraint=models.UniqueConstraint(
                fields=("field", "token"), name="uniq_keyword"
            ),
        ),
        migrations.AddField(
            model_name="querynode",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="query_nodes",
                to="core.campaign",
            ),
        ),
        migrations.AddField(
            model_name="querynode",
            name="keywords",
            field=models.ManyToManyField(related_name="nodes", to="core.keyword"),
        ),
        migrations.AddField(
            model_name="querynode",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="core.querynode",
            ),
        ),
        migrations.DeleteModel(
            name="EmptyClauseSet",
        ),
        migrations.RemoveField(
            model_name="discoveryquery",
            name="campaign",
        ),
        migrations.RemoveField(
            model_name="discoveryquery",
            name="clauses",
        ),
        migrations.AddIndex(
            model_name="querynode",
            index=models.Index(
                fields=["campaign", "state"], name="query_node_state_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="querynode",
            constraint=models.UniqueConstraint(
                fields=("campaign", "token_key"), name="uniq_query_node"
            ),
        ),
        migrations.DeleteModel(
            name="Clause",
        ),
    ]
