# Generated by Django 6.0.7 on 2026-07-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_keyword_querynode_remove_clause_uniq_clause_and_more"),
        ("crm", "0018_lead_source_fields_alter_lead_discovered_by"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DiscoveryQuery",
        ),
    ]
