# Generated by Django 6.0.6 on 2026-08-11 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_discoveryquery'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='core_task_status_sched_idx',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='action_fraction',
        ),
    ]
